function interfata(A,f,R,N,en)
close all;
    figure('Name','   Redresor mono alternanta fara filtru',...
           'Numbertitle','off',...  
           'Units','normalized',...    
           'Position',[0.01,0.01,0.9,0.9],...
           'Visible','on',...
           'Color',[0.2758 0.5157 0.4882]);


% Afisarea circuitului ====================================================
Img=imread('RM.jpg');
subplot(3,2,1);
image(Img);
grid on;
axis off;
%====== Titlu    
uicontrol('Style','text',...
          'Units','normalized',...
          'Position', [0.2 0.96 0.6 0.04],...
          'backgroundcolor', [0.8 0.9 0.9],...
          'foregroundcolor','black',...
          'fontweight', 'bold',...
          'fontsize', 20,...
          'String','Redresor mono alternanta fara filtru');

%====== Meniu
m=uimenu('Label','Proiect');
   uimenu(m,'Label','Autor','Callback','open(''Autor.pdf'')');    
   uimenu(m,'Label','Bibliografie','Callback','open(''Bibliografie.pdf'')');
   uimenu(m,'Label','Teorie','Callback','open(''Teorie.pdf'')');
   uimenu(m,'Label','Prezentare','Callback','open(''Prezentare.pptx'')');
   
%======= Chenar
P=uibuttongroup('Visible','on',...
        'BackgroundColor','white',...
        'ForegroundColor','black',...
        'Title','Setare Parametri',...
        'FontSize',15,...
        'Position',[0.1305 0.517 0.335 0.25],...
        'TitlePosition','centertop',...
        'Tag','radiobutton');
    
%======== A
uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.11 0.8 0.4 0.15],...
        'backgroundcolor',[0.4 0.4 0.4],...
        'foregroundcolor','white',...
        'FontSize',15,...
        'String','A [V]',...
        'Parent',P);
uicontrol('Style','edit',...
        'Units','normalized',...
        'Position',[0.55 0.8 0.3 0.12],...
        'FontSize',12,...
        'String', A,...
        'FontWeight','Bold',...
        'Parent',P,...
        'callback','A=str2num(get(gco,''string''));interfata(A,f,R,N,en)');
           
%========== f
uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.11 0.6 0.4 0.12],...
        'backgroundcolor',[0.4 0.4 0.4],...
        'foregroundcolor','white',...
        'FontSize',15,...
        'String','f [Hz]',...
        'Parent',P);
uicontrol('Style','edit',...
        'Units','normalized',...
        'Position',[0.55 0.6 0.3 0.12],...
        'FontSize',12,...
        'String', f,...
        'FontWeight','Bold',...
        'Parent',P,...
        'callback','f=str2num(get(gco,''string''));interfata(A,f,R,N,en)');


           
%========= R
uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.11 0.4 0.4 0.12],...
        'backgroundcolor',[0.4 0.4 0.4],...
        'foregroundcolor','white',...
        'FontSize',15,...
        'String','R [Ohm]',...
        'Parent',P);
uicontrol('Style','edit',...
        'Units','normalized',...
        'String',R,...
        'Position',[0.55 0.4 0.3 0.12],...
        'FontSize',12,...
        'FontWeight','Bold',...
        'Parent',P,...
        'callback','R=str2num(get(gco,''string''));interfata(A,f,R,N,en)');


%=========== N
uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.11 0.2 0.4 0.12],...
        'backgroundcolor',[0.4 0.4 0.4],...
        'foregroundcolor','white',...
        'FontSize',15,...
        'String','N',...
        'Parent',P);
uicontrol('Style','edit',...
        'Units','normalized',...
        'String',N,...
        'Position',[0.55 0.2 0.3 0.12],...
        'FontSize',12,...
        'FontWeight','Bold',...
        'Parent',P,...
        'callback','N=str2num(get(gco,''string''));interfata(A,f,R,N,en)'); 
    
%=======pushbutton
uicontrol('Style','pushbutton',...
        'Units','normalized',...
        'String','Redresare',...
        'Position',[0.25 0.38 0.1 0.12],...
        'FontSize',14,...
        'FontWeight','Bold',...
        'callback','en=2; interfata(A,f,R,N,en)');
    
% ecuatii =================================================================

           w=2.*pi.*f;
           T=1./f;
           t=0:T/100:N*T;       

           e1=A*sin(w*t);
           e2=abs(e1);

           e=e1;
           u=(e1+e2)/2;
           i=u/R;
           Umed=A/pi;
           Imed=Umed/R;
           Uef=A/2;
           
%==========================================================================           

% grafice =================================================================
    subplot(3,2,2);
      plot(t,e,'r');
      grid on;
      ylabel('e [ V ]', 'fontweight', 'bold');
      xlabel('t [ s ]', 'fontweight', 'bold');
      title('Semnalul de intrare','FontSize',14);
      if en==2
    subplot(3,2,4);
      plot(t,u,'b');
      grid on;
      ylabel('u [ V ]', 'fontweight', 'bold');
      xlabel('t [ s ]', 'fontweight', 'bold');
      title('Semnalul redresat','FontSize',14);
    subplot(3,2,6);
      plot(t,i,'g');grid on;
      ylabel('i [ A ]', 'fontweight', 'bold');
      xlabel('t [ s ]', 'fontweight', 'bold');
      title('Semnalul redresat','FontSize',14);
      end

% valori ==================================================================
Val=uibuttongroup('Visible','off',...
        'BackgroundColor','white',...
        'ForegroundColor','black',...
        'Title','Valori',...
        'FontSize',15,...
        'Position',[0.13 0.11 0.336 0.21],...
        'TitlePosition','centertop',...
        'Tag','radiobutton');
    
%======= Umed
uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.11 0.8 0.4 0.16],...
        'backgroundcolor',[0.4 0.4 0.4],...
        'foregroundcolor','white',...
        'FontSize',15,...
        'String','Umed = ',...
        'HorizontalAlignment', 'right',...
        'Parent',Val);
uicontrol('Style','edit',...
        'Units','normalized',...
        'Position',[0.55 0.8 0.3 0.12],...
        'FontSize',12,...
        'FontWeight', 'bold',...
        'HorizontalAlignment', 'left',...
        'String', num2str(Umed),...
        'Parent',Val);
    
%====== Imed
uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.11 0.44 0.4 0.16],...
        'backgroundcolor',[0.4 0.4 0.4],...
        'foregroundcolor','white',...
        'FontSize',15,...
        'HorizontalAlignment', 'right',...
        'String','Imed = ',...
        'Parent',Val);
uicontrol('Style','edit',...
        'Units','normalized',...
        'Position',[0.55 0.44 0.3 0.12],...
        'FontSize',12,...
        'FontWeight', 'bold',...
        'HorizontalAlignment', 'left',...
        'String', num2str(Imed),...
        'Parent',Val);
    
%======= Uef
uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.11 0.1 0.4 0.16],...
        'backgroundcolor',[0.4 0.4 0.4],...
        'foregroundcolor','white',...
        'FontSize',15,...
        'HorizontalAlignment', 'right',...
        'String','Uef = ',...
        'Parent',Val);
uicontrol('Style','edit',...
        'Units','normalized',...
        'String',num2str(Uef),...
        'Position',[0.55 0.1 0.3 0.12],...
        'FontSize',12,...
        'FontWeight', 'bold',...
        'HorizontalAlignment', 'left',...
        'Parent',Val);

if en==2
Val.Visible = 'on';
end

  subplot(3,2,5);

 axis off;

 %------------------------------
%=======================================================
